### ISSUE TITLE
Android throwing an error

### ISSUE THREAD

**Issue by NotTooReact89** [b8ne/react-native-pusher-push-notifications#45]
Hi therem

Please help. Below is the stacktrace

2019-08-06 22:16:58.539 9006-10000/com.xxx.xxx E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
    Process: com.xxxx.xxx, PID: 9006
    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.b8ne.RNPusherPushNotifications.PusherWrapper.unsubscribe(java.lang.String, com.facebook.react.bridge.Callback, com.facebook.react.bridge.Callback)' on a null object reference
        at com.b8ne.RNPusherPushNotifications.RNPusherPushNotificationsModule$2.run(RNPusherPushNotificationsModule.java:46)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)

**Comment by Ahmdrza** [comment]
@NotTooReact89 Hi did you find any solution for this? I have to explicitly call setIntanceId every time before using any function which introduces more bugs.

**Comment by Humni** [comment]
There isn't enough information to reproduce this issue - closing this and will re-open if more information is provided
